# -*- coding: utf-8 -*-
"""Projeto_streamlit_TED_do_HGPipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZI0xFPwffLrF7Ot96xheCiYy_P5qjj1G
"""

import streamlit as st
import pandas as pd
import io

# URL do CSV no GitHub (RAW)
CSV_URL = "https://github.com/held95/ted_hgp_neuro/raw/refs/heads/main/HOSP%20NCR%20-%2016-06-25%20a%2015-07-25.csv"

# Função para carregar dados
@st.cache_data
def carregar_dados():
    return pd.read_csv(CSV_URL)

# Título
st.title("Editor de Dados do GitHub CSV")

# Carregar dados
df = carregar_dados()

st.subheader("Visualizar e Editar Dados")
edit_df = st.data_editor(df, use_container_width=True, num_rows="dynamic")

# Mostrar os dados editados
st.subheader("Dados Atualizados")
st.dataframe(edit_df, use_container_width=True)

# Botão para baixar CSV atualizado
csv = edit_df.to_csv(index=False).encode('utf-8')
st.download_button(
    label="📥 Baixar CSV Atualizado",
    data=csv,
    file_name="dados_editados.csv",
    mime="text/csv"
)
